//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVO.Astronomy.TheSkyX.Properties
{
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HVO.Astronomy.TheSkyX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string for the TheSkyXClientScript_Initialize resource.
        /// </summary>
        internal static string TheSkyXClientScript_Initialize
        {
            get
            {
                return ResourceManager.GetString("TheSkyXClientScript_Initialize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the TheSkyXScript_GetBinList resource.
        /// </summary>
        internal static string TheSkyXScript_GetBinList
        {
            get
            {
                return ResourceManager.GetString("TheSkyXScript_GetBinList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the TheSkyXScript_GetFilterList resource.
        /// </summary>
        internal static string TheSkyXScript_GetFilterList
        {
            get
            {
                return ResourceManager.GetString("TheSkyXScript_GetFilterList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the TheSkyXScript_GetImageLinkResults resource.
        /// </summary>
        internal static string TheSkyXScript_GetImageLinkResults
        {
            get
            {
                return ResourceManager.GetString("TheSkyXScript_GetImageLinkResults", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the TheSkyXScript_GetObservatoryInformation resource.
        /// </summary>
        internal static string TheSkyXScript_GetObservatoryInformation
        {
            get
            {
                return ResourceManager.GetString("TheSkyXScript_GetObservatoryInformation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the TheSkyXScript_GetSelectedHardware resource.
        /// </summary>
        internal static string TheSkyXScript_GetSelectedHardware
        {
            get
            {
                return ResourceManager.GetString("TheSkyXScript_GetSelectedHardware", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the TheSkyXScript_StarChartClickFindXY resource.
        /// </summary>
        internal static string TheSkyXScript_StarChartClickFindXY
        {
            get
            {
                return ResourceManager.GetString("TheSkyXScript_StarChartClickFindXY", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the TheSkyXScript_StarChartFindByName resource.
        /// </summary>
        internal static string TheSkyXScript_StarChartFindByName
        {
            get
            {
                return ResourceManager.GetString("TheSkyXScript_StarChartFindByName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the TheSkyXScript_TakeImageStatus resource.
        /// </summary>
        internal static string TheSkyXScript_TakeImageStatus
        {
            get
            {
                return ResourceManager.GetString("TheSkyXScript_TakeImageStatus", resourceCulture);
            }
        }
    }
}
